# syntax=docker/dockerfile:1
#
# HOL4 building environment (Docker), the CI image
#
# NOTE: this docker image is NOT for HOL developers to use interactively.

# This "base" image is described in "base/Dockerfile"
FROM --platform=$TARGETPLATFORM binghelisp/hol-dev:more-solvers

# The following two arguments are supported by "docker buildx" commands
ARG TARGETPLATFORM
ARG BUILDPLATFORM

# GitHub Actions' hardware specification for Linux virtual machines: 2-core CPU (x86_64)
# By default we use 4 cores in other building environments (e.g. Docker Hub autobuilds)
ARG BUILDOPTS="--expk -j4"
ARG SML=poly

WORKDIR /ML/HOL

# fast copy all files to the docker image
COPY --link . .

# set up extra environment variables
ENV HOL4_Z3_EXECUTABLE=/ML/z3-2.19/bin/z3
ENV HOL4_CVC_EXECUTABLE=/ML/cvc5-Linux

# remove poly-includes.ML for docker builds
RUN rm -f tools-poly/poly-includes.ML

# building HOL
RUN ${SML} < tools/smart-configure.sml 
RUN bin/build ${BUILDOPTS}

# This can be overrided by "docker run <command>"
CMD ["/ML/HOL/bin/hol"]
