name: docker-arm64

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: 'HOL kernel'
        required: true
        default: 'expk'
        type: choice
        options:
        - stdknl
        - expk
        - otknl
      concurrency:
        description: 'Concurrency'
        required: true
        default: '2'
        type: number
      other-options:
        description: 'Other options'
        required: false
        type: string
jobs:
  build-expk:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/hol-dev
          tags: |
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-,suffix=-arm64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: developers/docker-ci/Dockerfile.arm64
          platforms: linux/arm64/v8
          push: true
          build-args: |
            SML=poly
            # NOTE: the arg value cannot be quoted here:
            BUILDOPTS=--${{ github.event.inputs.kernel }} -j${{ github.event.inputs.concurrency }} ${{ github.event.inputs.other-options }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
