name: self-runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Building environment'
        required: true
        default: 'self-hosted'
        type: choice
        options:
        - self-hosted
        - ubuntu-latest
      platform:
        description: 'Building platform'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
        - linux/amd64
        - linux/arm64/v8
      dockerfile:
        description: 'Dockerfile'
        required: true
        default: 'Dockerfile'
        type: choice
        options:
        - Dockerfile
        - Dockerfile.arm64
      kernel:
        description: 'HOL kernel'
        required: true
        default: 'expk'
        type: choice
        options:
        - stdknl
        - expk
        - otknl
      concurrency:
        description: 'Concurrency'
        required: true
        default: '4'
        type: number
      other-options:
        description: 'More options'
        required: false
        type: string

  pull_request:
    branches:
      - "develop"
      - "probability_dev"
  push:
    branches:
      - "master"
      - "develop"
      - "probability_dev"

jobs:
  build:
    runs-on: ${{ github.event.inputs.environment }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/hol-dev
          tags: |
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-,suffix=-self
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: developers/docker-ci/${{ github.event.inputs.dockerfile }}
          platforms: ${{ github.event.inputs.platform }}
          push: true
          build-args: |
            SML=poly
            # NOTE: the arg value cannot be quoted here:
            BUILDOPTS=--${{ github.event.inputs.kernel }} -j${{ github.event.inputs.concurrency }} ${{ github.event.inputs.more-options }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
