name: self-runner

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: 'HOL kernel'
        required: true
        default: 'expk'
        type: choice
        options:
        - stdknl
        - expk
        - otknl
      concurrency:
        description: 'Concurrency'
        required: true
        default: '2'
        type: number
      more-options:
        description: 'More options'
        required: false
        type: string

  pull_request:
    branches:
      - "develop"
      - "probability_dev"

  push:
    branches:
      - "master"
      - "develop"
      - "probability_dev"

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/hol-dev
          tags: |
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-,suffix=-self
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: true
          build-args: |
            SML=poly
            # NOTE: the arg value cannot be quoted here:
            BUILDOPTS=--${{ inputs.kernel }} -j${{ inputs.concurrency }} ${{ inputs.more-options }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
